(() => {
  "use strict";
  const API=(window.POKEMAP_CONFIG?.apiBase||"").replace(/\/$/,"");
  const CONFIG=window.POKEMAP_CONFIG||{};
  const ACCESS_KEY=new URLSearchParams(location.hash.slice(1)).get("access")||"";
  const GEOFENCE={enabled:CONFIG.geofence?.enabled!==false&&!ACCESS_KEY,latitude:Number(CONFIG.geofence?.latitude),longitude:Number(CONFIG.geofence?.longitude),radiusKm:Number(CONFIG.geofence?.radiusKm)};
  const REPORTER_ID=loadReporterId();
  const REPORT_API=(CONFIG.reportApiBase||API).replace(/\/$/,"");
  const UNKNOWN_ENCOUNTER={id:"unknown-encounter",label:"Unknown encounter",type:"ENCOUNTER",image:"https://cdn.discordapp.com/emojis/1321211297668268063.webp?size=96"};
  const REGULAR_QUEST_ID="regular-quest";
  const NIANTIC_QUERY=`query MapFallback($input: RealityChannelMapObjectsByS2CellsInput!) { realityChannelMapObjectsByS2Cells(input: $input) { mapObjectsByS2CellsAndTypes { s2CellId mapObjectsByType { type mapObjects { id pgoGym { name location { latitude longitude } } pgoPokestop { name location { latitude longitude } } } } } } }`;
  const nianticCache=new Map();
  const state={mode:"research",pois:[],knownPois:new Map(),catalogue:[],reportsByStop:new Map(),questFilter:loadQuestFilter(),completedResearch:loadCompletedResearch(),selected:null,selectedReports:[]};
  const savedView=loadSavedView();
  const latitudeSpan=GEOFENCE.radiusKm/111.32,longitudeSpan=GEOFENCE.radiusKm/(111.32*Math.cos(GEOFENCE.latitude*Math.PI/180));
  const communityBounds=L.latLngBounds([GEOFENCE.latitude-latitudeSpan,GEOFENCE.longitude-longitudeSpan],[GEOFENCE.latitude+latitudeSpan,GEOFENCE.longitude+longitudeSpan]);
  const map=L.map("map",{zoomControl:false,minZoom:11,maxZoom:19,...(GEOFENCE.enabled?{maxBounds:communityBounds,maxBoundsViscosity:1}:{})}).setView([savedView.latitude,savedView.longitude],savedView.zoom);
  map.createPane("interactionRanges");map.getPane("interactionRanges").style.zIndex="425";map.getPane("interactionRanges").style.pointerEvents="none";map.getPane("interactionRanges").classList.add("leaflet-interaction-pane");
  map.createPane("s2Labels");map.getPane("s2Labels").style.zIndex="450";
  L.control.zoom({position:"bottomright"}).addTo(map);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
  if(GEOFENCE.enabled)L.circle([GEOFENCE.latitude,GEOFENCE.longitude],{radius:GEOFENCE.radiusKm*1000,color:"#52e0a4",weight:2,opacity:.75,fill:false,interactive:false}).addTo(map);
  const poiLayer=L.layerGroup(),radiusLayer=L.layerGroup(),interactionLayer=L.layerGroup(),cells17=L.layerGroup(),cells14=L.layerGroup(),locationLayer=L.layerGroup(),cellRenderer=L.canvas({padding:.5}),interactionRenderer=L.canvas({padding:.5,pane:"interactionRanges"});
  map.addLayer(radiusLayer);map.addLayer(cells17);map.addLayer(cells14);map.addLayer(interactionLayer);map.addLayer(poiLayer);map.addLayer(locationLayer);
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const escape=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const api=async(path,options={})=>{const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok){let m=`Request failed (${r.status})`;try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r.status===204?null:r.json()};
  const reportApi=async(path,options={})=>{const r=await fetch(REPORT_API+path,{...options,headers:{"Content-Type":"application/json",...(ACCESS_KEY?{"X-Geofence-Bypass":ACCESS_KEY}:{}),...(options.headers||{})}});if(!r.ok){let m=`Request failed (${r.status})`;try{m=(await r.json()).error||m}catch{}throw new Error(m)}return r.status===204?null:r.json()};
  function loadSavedView(){try{const view=JSON.parse(localStorage.getItem("pokemap-view-v1"));if(Number.isFinite(view?.latitude)&&Number.isFinite(view?.longitude)&&Number.isInteger(view?.zoom)&&view.zoom>=11&&view.zoom<=19&&withinGeofence(view.latitude,view.longitude))return view}catch{}return{latitude:GEOFENCE.latitude,longitude:GEOFENCE.longitude,zoom:14}}
  function saveView(){try{const center=map.getCenter();localStorage.setItem("pokemap-view-v1",JSON.stringify({latitude:center.lat,longitude:center.lng,zoom:map.getZoom()}))}catch{}}
  function loadReporterId(){try{const saved=localStorage.getItem("pokemap-reporter-id-v1");if(/^[A-Za-z0-9_-]{20,100}$/.test(saved||""))return saved;const created=crypto.randomUUID?.()||[...crypto.getRandomValues(new Uint8Array(24))].map(value=>value.toString(16).padStart(2,"0")).join("");localStorage.setItem("pokemap-reporter-id-v1",created);return created}catch{return `session-${Date.now()}-${Math.random().toString(36).slice(2)}`}}
  function distanceKm(latitude,longitude){const radians=value=>value*Math.PI/180,latitudeDelta=radians(latitude-GEOFENCE.latitude),longitudeDelta=radians(longitude-GEOFENCE.longitude),a=Math.sin(latitudeDelta/2)**2+Math.cos(radians(GEOFENCE.latitude))*Math.cos(radians(latitude))*Math.sin(longitudeDelta/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
  function withinGeofence(latitude,longitude){return Number.isFinite(latitude)&&Number.isFinite(longitude)&&(!GEOFENCE.enabled||distanceKm(latitude,longitude)<=GEOFENCE.radiusKm)}
  function loadQuestFilter(){try{const saved=JSON.parse(localStorage.getItem("pokemap-quest-filter-v1"));if(saved&&Array.isArray(saved.selected))return{active:Boolean(saved.active),selected:new Set(saved.selected.map(String)),showUnreported:saved.showUnreported!==false}}catch{}return{active:false,selected:new Set(),showUnreported:true}}
  function saveQuestFilter(){try{localStorage.setItem("pokemap-quest-filter-v1",JSON.stringify({active:state.questFilter.active,selected:[...state.questFilter.selected],showUnreported:state.questFilter.showUnreported}))}catch{}}
  function localDayKey(){const now=new Date();return`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`}
  function loadCompletedResearch(){const day=localDayKey();try{const saved=JSON.parse(localStorage.getItem("pokemap-completed-research-v1"));if(saved?.day===day&&Array.isArray(saved.keys))return{day,keys:new Set(saved.keys.map(String))}}catch{}return{day,keys:new Set()}}
  function completedResearchState(){const day=localDayKey();if(state.completedResearch.day!==day)state.completedResearch={day,keys:new Set()};return state.completedResearch}
  function completedResearchKey(stopId,taskId,rewardId){return`${stopId}::${taskId}::${rewardId}`}
  function isResearchCompleted(stopId,taskId,rewardId){return completedResearchState().keys.has(completedResearchKey(stopId,taskId,rewardId))}
  function toggleResearchCompleted(stopId,taskId,rewardId){const completed=completedResearchState(),key=completedResearchKey(stopId,taskId,rewardId);if(completed.keys.has(key))completed.keys.delete(key);else completed.keys.add(key);try{localStorage.setItem("pokemap-completed-research-v1",JSON.stringify({day:completed.day,keys:[...completed.keys]}))}catch{}return completed.keys.has(key)}
  const questKey=report=>`${report.taskId}::${report.rewardId}`;
  function typeOf(p){return String(p.type||"").toUpperCase().replace(/[É_ ]/g,c=>c==="É"?"E":"")}
  function stopDotRadius(){const zoom=map.getZoom();return zoom>=19?18:zoom>=18?14:Math.max(5,Math.min(10,zoom-10))}
  function icon(type,reward){if(type==="POKESTOP"&&reward?.regular){const radius=stopDotRadius(),size=radius*2;return L.divIcon({className:"",html:`<div class="regular-quest-icon${reward.completed?" completed":""}" style="width:${size}px;height:${size}px">${reward.conflict?'<span class="reward-conflict">!</span>':""}</div>`,iconSize:[size,size],iconAnchor:[radius,radius],popupAnchor:[0,-radius-2]})}if(type==="POKESTOP"&&reward?.image){const taskBadge=reward.taskIcon?`<span class="task-kind-badge" title="${escape(reward.taskKind)} task"><img src="${escape(reward.taskIcon)}" alt="${escape(reward.taskKind)} task"></span>`:reward.taskEmoji?`<span class="task-kind-badge" title="${escape(reward.taskKind)} task" aria-label="${escape(reward.taskKind)} task">${escape(reward.taskEmoji)}</span>`:"",scale=Math.max(.75,Math.min(1,.75+(map.getZoom()-15)/12));return L.divIcon({className:"",html:`<div class="reward-icon reward-${escape(slug(reward.label))}${reward.completed?" completed":""}" style="transform:scale(${scale.toFixed(3)})"><img src="${escape(reward.image)}" alt="${escape(reward.label)}" loading="lazy" decoding="async">${taskBadge}${reward.conflict?'<span class="reward-conflict">!</span>':""}${reward.completed?'<span class="reward-completed" title="Completed locally">✓</span>':""}</div>`,iconSize:[50,50],iconAnchor:[25,25],popupAnchor:[0,-27]})}const key=type==="GYM"?"gym":"stop";return L.divIcon({className:"",html:`<div class="poi-icon ${key}"><span>${type==="GYM"?"★":"●"}</span></div>`,iconSize:[29,29],iconAnchor:[14,28]})}
  function directions(lat,lng){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(lat+","+lng)}`}
  function directionsAction(p){return`<a class="icon-action" href="${directions(p.latitude,p.longitude)}" target="_blank" rel="noopener" aria-label="Open directions" title="Open directions"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 5 6-3 6 3 6-3v17l-6 3-6-3-6 3V5Zm7-1v13.3l4 2V6.7l-4-2V4Zm-5 2.2v12.6l3-1.5V4.7L5 6.2Zm11 .5v12.6l3-1.5V5.2l-3 1.5Z"/></svg></a>`}
  function hasActiveResearchEvent(){return state.catalogue.some(task=>task.timedEventPriority)}
  function reportsForStop(stopId){const reports=state.reportsByStop.get(stopId)||[];return state.questFilter.active?reports.filter(report=>state.questFilter.selected.has(questKey(report))):reports}
  function isRegularReport(report){return report?.taskId===REGULAR_QUEST_ID&&report?.rewardId===REGULAR_QUEST_ID}
  function taskKindFor(taskId){const text=plainText(state.catalogue.find(task=>task.id===taskId)?.text||"").toLocaleLowerCase("en");if(/purif/.test(text))return{emoji:"🫧",label:"Purify"};if(/shadow pok/.test(text))return{emoji:"👻",label:"Shadow"};if(/snapshot|photo/.test(text))return{emoji:"📸",label:"Snapshot"};if(/hatch/.test(text))return{emoji:"🥚",label:"Hatch"};if(/trad/.test(text))return{emoji:"🔄",label:"Trade"};if(/buddy|heart|candy walking/.test(text))return{emoji:"❤️",label:"Buddy"};if(/power up/.test(text))return{emoji:"⬆️",label:"Power up"};if(/rocket|grunt|leader/.test(text))return{emoji:"🚀",label:"Team GO Rocket"};if(/spin|explor|walk|route|visit/.test(text))return{emoji:"🧭",label:"Explore"};if(/battle|raid|gym/.test(text))return{emoji:"⚔️",label:"Battle"};if(/throw/.test(text))return{emoji:"🎯",label:"Throw"};if(/catch|berry/.test(text))return{icon:"assets/poke-ball-icon.svg",label:"Catch"};return{emoji:"📋",label:"Other"}}
  function displayedReportsForStop(stopId,rewardQuery=""){const reports=reportsForStop(stopId);if(!rewardQuery)return reports;const matches=reports.filter(report=>rewardName(report.taskId,report.rewardId).toLocaleLowerCase("en").includes(rewardQuery));return matches.length?matches:reports}
  function rewardForStop(stopId,rewardQuery="",excludeRegular=false){const allReports=state.reportsByStop.get(stopId)||[];let reports=displayedReportsForStop(stopId,rewardQuery);if(excludeRegular)reports=reports.filter(report=>!isRegularReport(report));if(!reports.length)return null;const best=[...reports].sort((a,b)=>(b.confirmationCount||0)-(a.confirmationCount||0)||String(b.lastReportedAt||"").localeCompare(String(a.lastReportedAt||"")))[0],completed=isResearchCompleted(stopId,best.taskId,best.rewardId),conflict=allReports.length>1||allReports.some(report=>report.needsReview);if(isRegularReport(best))return{regular:true,label:"Non event quest",completed:false,conflict};const task=state.catalogue.find(item=>item.id===best.taskId),reward=task?.rewards.find(item=>item.id===best.rewardId),kind=taskKindFor(best.taskId);return reward?.image?{image:reward.image,label:reward.label,taskEmoji:kind.emoji,taskIcon:kind.icon,taskKind:kind.label,completed,conflict}:null}
  function researchTooltip(p){const query=$("#search").value.trim().toLocaleLowerCase("en"),rewardQuery=query&&!String(p.name||"").toLocaleLowerCase("en").includes(query)?query:"";let reports=displayedReportsForStop(p.id,rewardQuery);if(map.getZoom()<15)reports=reports.filter(report=>!isRegularReport(report));if(!reports.length)return null;const best=[...reports].sort((a,b)=>(b.confirmationCount||0)-(a.confirmationCount||0)||String(b.lastReportedAt||"").localeCompare(String(a.lastReportedAt||"")))[0];return `<strong>${escape(p.name||"Unnamed PokéStop")}</strong><span>${escape(taskName(best.taskId))}</span>`}
  function addResearchTooltip(marker,p){const content=researchTooltip(p),hasTask=Boolean(content);marker.bindTooltip(content||`<strong>${escape(p.name||"Unnamed PokéStop")}</strong>`,{className:`research-hover${hasTask?"":" name-only"}`,direction:"top",offset:[0,-18]});return marker}
  function passesQuestFilter(p,type){if(state.mode==="planner"||type!=="POKESTOP")return true;const reports=state.reportsByStop.get(p.id)||[];return reports.length?reportsForStop(p.id).length>0:state.questFilter.showUnreported}
  function matchesMapSearch(p,type,query){if(!query)return true;if(String(p.name||"").toLocaleLowerCase("en").includes(query))return true;if(state.mode!=="research"||type!=="POKESTOP")return false;return reportsForStop(p.id).some(report=>rewardName(report.taskId,report.rewardId).toLocaleLowerCase("en").includes(query))}
  function rememberPois(pois){state.pois=pois;for(const poi of pois)state.knownPois.set(poi.id,poi)}
  function reportClusterIcon(count){return L.divIcon({className:"",html:`<div class="report-cluster"><strong>${count}</strong><span aria-hidden="true">🔍</span></div>`,iconSize:[52,52],iconAnchor:[26,26]})}
  function renderReportClusters(entries){const groups=[],zoom=map.getZoom(),mergeDistance=150;for(const entry of entries){const point=map.project([entry.p.latitude,entry.p.longitude],zoom),group=groups.find(candidate=>candidate.center.distanceTo(point)<=mergeDistance);if(group){const previous=group.entries.length;group.entries.push(entry);group.center=L.point((group.center.x*previous+point.x)/(previous+1),(group.center.y*previous+point.y)/(previous+1))}else groups.push({center:point,entries:[entry]})}let changed=true;while(changed){changed=false;outer:for(let left=0;left<groups.length;left++)for(let right=left+1;right<groups.length;right++)if(groups[left].center.distanceTo(groups[right].center)<=mergeDistance){const a=groups[left],b=groups[right],total=a.entries.length+b.entries.length;a.center=L.point((a.center.x*a.entries.length+b.center.x*b.entries.length)/total,(a.center.y*a.entries.length+b.center.y*b.entries.length)/total);a.entries.push(...b.entries);groups.splice(right,1);changed=true;break outer}}for(const cluster of groups){const group=cluster.entries,count=group.length;if(count===1){const entry=group[0],marker=addResearchTooltip(L.marker([entry.p.latitude,entry.p.longitude],{icon:icon(entry.t,entry.reward)}),entry.p);marker.on("click",()=>openPoi(entry.p)).addTo(poiLayer);continue}const center=map.unproject(cluster.center,zoom),marker=L.marker(center,{icon:reportClusterIcon(count),title:`${count} reported research locations`});marker.on("click",()=>map.fitBounds(L.latLngBounds(group.map(entry=>[entry.p.latitude,entry.p.longitude])),{padding:[45,45],maxZoom:15})).addTo(poiLayer)}}
  function renderPois(){poiLayer.clearLayers();const q=$("#search").value.trim().toLocaleLowerCase("en"),enabled=new Set($$("[data-filter]:checked").map(x=>x.dataset.filter)),zoomedOut=map.getZoom()<15,dotRadius=stopDotRadius(),source=state.mode==="research"&&zoomedOut?[...state.knownPois.values()]:state.pois,entries=[];for(const p of source){const t=typeOf(p),hasDetailedReport=reportsForStop(p.id).some(report=>!isRegularReport(report));if(state.mode==="research"&&zoomedOut&&!hasDetailedReport||!withinGeofence(Number(p.latitude),Number(p.longitude))||t==="GYM"&&state.mode!=="planner"||!enabled.has(t)||!passesQuestFilter(p,t)||!matchesMapSearch(p,t,q))continue;const rewardQuery=state.mode==="research"&&q&&!String(p.name||"").toLocaleLowerCase("en").includes(q)?q:"";entries.push({p,t,reward:state.mode==="research"?rewardForStop(p.id,rewardQuery,zoomedOut):null})}if(state.mode==="research"&&map.getZoom()<14)renderReportClusters(entries);else for(const {p,t,reward} of entries){let marker=reward?L.marker([p.latitude,p.longitude],{icon:icon(t,reward)}):L.circleMarker([p.latitude,p.longitude],{renderer:cellRenderer,radius:t==="GYM"?dotRadius+2:dotRadius,color:"#eafcff",weight:2,fillColor:t==="GYM"?"#e84b57":"#168ee3",fillOpacity:1});if(state.mode==="research"&&t==="POKESTOP")marker=addResearchTooltip(marker,p);marker.on("click",()=>openPoi(p)).addTo(poiLayer)}renderRadii();renderInteractionRanges()}
  function renderRadii(){radiusLayer.clearLayers();if(state.mode!=="planner"||map.getZoom()<15||!$("#radius20").checked)return;const q=$("#search").value.trim().toLowerCase(),enabled=new Set($$("[data-filter]:checked").map(x=>x.dataset.filter));for(const p of state.pois){const type=typeOf(p);if(!withinGeofence(Number(p.latitude),Number(p.longitude))||!enabled.has(type)||!passesQuestFilter(p,type)||q&&!p.name.toLowerCase().includes(q))continue;L.circle([p.latitude,p.longitude],{renderer:cellRenderer,radius:20,color:"#52e0a4",weight:1,opacity:.9,fillColor:"#52e0a4",fillOpacity:.12,interactive:false}).addTo(radiusLayer)}}
  function renderInteractionRanges(){interactionLayer.clearLayers();if(state.mode!=="planner"||map.getZoom()<15)return;const ranges=[];if($("#stopRange80").checked)ranges.push({type:"POKESTOP",radius:80,color:"#c06cff",fillOpacity:.14,lineOpacity:.95,weight:2.25});if($("#stopRange40").checked)ranges.push({type:"POKESTOP",radius:40,color:"#35d5ff",fillOpacity:.09,lineOpacity:.9,weight:2});if($("#gymRange80").checked)ranges.push({type:"GYM",radius:80,color:"#ff7a8a",fillOpacity:.075,lineOpacity:.9,weight:2});if(!ranges.length)return;if($("#rangeHotspots").checked){renderRangeHotspots();return}for(const p of state.pois){const type=typeOf(p);if(!withinGeofence(Number(p.latitude),Number(p.longitude)))continue;for(const range of ranges)if(type===range.type)L.circle([p.latitude,p.longitude],{renderer:interactionRenderer,radius:range.radius,color:range.color,weight:range.weight,opacity:range.lineOpacity,fillColor:range.color,fillOpacity:range.fillOpacity,interactive:false}).addTo(interactionLayer)}}
  function renderRangeHotspots(){const stopRadius=$("#stopRange80").checked?80:$("#stopRange40").checked?40:0,gymRadius=$("#gymRange80").checked?80:0;if(!stopRadius&&!gymRadius)return;const center=map.getCenter(),centerPoint=map.latLngToContainerPoint(center),metersToPixels=map.latLngToContainerPoint([center.lat+80/111320,center.lng]).distanceTo(centerPoint)/80,pois=[];for(const p of state.pois){const type=typeOf(p),radius=type==="POKESTOP"?stopRadius:type==="GYM"?gymRadius:0;if(radius&&withinGeofence(Number(p.latitude),Number(p.longitude)))pois.push({point:map.latLngToContainerPoint([p.latitude,p.longitude]),radiusSquared:(radius*metersToPixels)**2})}if(pois.length<2)return;const size=map.getSize(),step=24,samples=[];let maximum=0;for(let y=step/2;y<size.y;y+=step)for(let x=step/2;x<size.x;x+=step){let count=0;for(const poi of pois){const dx=x-poi.point.x,dy=y-poi.point.y;if(dx*dx+dy*dy<=poi.radiusSquared)count++}if(count>=2){maximum=Math.max(maximum,count);samples.push({point:L.point(x,y),count})}}if(maximum<2)return;for(const sample of samples){const strength=maximum===2?1:(sample.count-2)/(maximum-2),hue=38+18*strength,lightness=38+36*strength,northWest=map.containerPointToLatLng([sample.point.x-step/2,sample.point.y-step/2]),southEast=map.containerPointToLatLng([sample.point.x+step/2,sample.point.y+step/2]);L.rectangle(L.latLngBounds(northWest,southEast),{renderer:interactionRenderer,stroke:false,fillColor:`hsl(${hue} 100% ${lightness}%)`,fillOpacity:.22+.5*strength,interactive:false}).addTo(interactionLayer)}}
  async function toggleCompletedFromSheet(p,report){const wasCompleted=isResearchCompleted(p.id,report.taskId,report.rewardId);if(!wasCompleted&&!report.confirmedByYou)try{await reportApi("/api/research/report",{method:"POST",body:JSON.stringify({pokestopId:p.id,taskId:report.taskId,rewardId:report.rewardId,latitude:p.latitude,longitude:p.longitude,reporterId:REPORTER_ID,turnstileToken:null})});playReportFireworks(Number(p.latitude),Number(p.longitude));toast("Thank you for the report!");state.selectedReports=await reportApi(`/api/research?pokestopId=${encodeURIComponent(p.id)}&reporterId=${encodeURIComponent(REPORTER_ID)}`)}catch(error){toast(error.message);return}toggleResearchCompleted(p.id,report.taskId,report.rewardId);closeSheet();state.selected=null;state.selectedReports=[];renderPois();if(!wasCompleted)loadStatic()}
  async function submitRegularQuest(p){try{await reportApi("/api/research/report",{method:"POST",body:JSON.stringify({pokestopId:p.id,taskId:REGULAR_QUEST_ID,rewardId:REGULAR_QUEST_ID,latitude:p.latitude,longitude:p.longitude,reporterId:REPORTER_ID,turnstileToken:null})});closeSheet();playReportFireworks(Number(p.latitude),Number(p.longitude));state.selected=null;state.selectedReports=[];toast("Thank you for the report!");await loadStatic()}catch(error){toast(error.message);$("#regularQuest")?.removeAttribute("disabled")}}
  function renderResearchPoiSheet(p){const candidates=state.selectedReports||[],quests=candidates.length?candidates.map(c=>{const canComplete=c.taskId!==REGULAR_QUEST_ID||c.rewardId!==REGULAR_QUEST_ID,completed=canComplete&&isResearchCompleted(p.id,c.taskId,c.rewardId),action=completed?"Mark research incomplete":"Mark research complete",completeButton=canComplete?`<button type="button" class="quest-complete" data-task-id="${escape(c.taskId)}" data-reward-id="${escape(c.rewardId)}" aria-pressed="${completed}" aria-label="${action}" title="${action}, saved on this device for today">✓</button>`:"";return`<div class="quest${completed?" completed":""}${canComplete?"":" no-complete"}"><div><strong>${escape(taskName(c.taskId))}</strong><span>${escape(rewardName(c.taskId,c.rewardId))} · ${c.confirmationCount} confirmation${c.confirmationCount===1?"":"s"}${c.needsReview?" · ⚠ conflict":""}</span></div>${completeButton}</div>`}).join(""):`<p>No research has been reported here today.</p>`,quickRegular=typeOf(p)==="POKESTOP"&&hasActiveResearchEvent()?'<button id="regularQuest" class="secondary">Non event quest</button>':"";$("#sheetContent").innerHTML=`<span class="badge">${escape(typeOf(p))}</span><h2>${escape(p.name||"Unnamed Wayspot")}</h2>${typeOf(p)==="POKESTOP"?quests:""}<div class="sheet-actions">${directionsAction(p)}${quickRegular}${typeOf(p)==="POKESTOP"?'<button id="reportHere" class="primary">Report details</button>':""}</div>`;showSheet();$("#reportHere")?.addEventListener("click",openReport);$("#regularQuest")?.addEventListener("click",event=>{event.currentTarget.disabled=true;submitRegularQuest(p)});$$('.quest-complete').forEach(button=>button.addEventListener("click",async()=>{const report=candidates.find(candidate=>candidate.taskId===button.dataset.taskId&&candidate.rewardId===button.dataset.rewardId);if(!report)return;button.disabled=true;await toggleCompletedFromSheet(p,report);if(button.isConnected)button.disabled=false}))}
  async function openPoi(p){state.selected=p;if(state.mode==="planner"){state.selectedReports=[];$("#sheetContent").innerHTML=`<span class="badge">${escape(typeOf(p))}</span><h2>${escape(p.name||"Unnamed Wayspot")}</h2><div class="sheet-actions">${directionsAction(p)}</div>`;showSheet();return}let candidates=[];if(typeOf(p)==="POKESTOP")try{candidates=await reportApi(`/api/research?pokestopId=${encodeURIComponent(p.id)}&reporterId=${encodeURIComponent(REPORTER_ID)}`)}catch(e){toast(e.message)}state.selectedReports=candidates;renderResearchPoiSheet(p)}
  function showSheet(){$("#sheet").classList.add("open");$("#sheetBackdrop").classList.remove("hidden")}function closeSheet(){$("#sheet").classList.remove("open");$("#sheetBackdrop").classList.add("hidden")}
  function plainText(value){const el=document.createElement("span");el.innerHTML=String(value??"");return el.textContent.trim()}
  function mergeDuplicateTasks(tasks){const output=[],byText=new Map();for(const task of tasks||[]){const key=plainText(task.text).replace(/\s+/g," ").trim().toLocaleLowerCase("en"),existing=byText.get(key);if(!key)continue;if(!existing){const copy={...task,rewards:(task.rewards||[]).map(reward=>({...reward}))};byText.set(key,copy);output.push(copy);continue}const rewards=new Map(existing.rewards.map(reward=>[reward.id,reward]));for(const reward of task.rewards||[]){const known=rewards.get(reward.id);if(!known){const copy={...reward};existing.rewards.push(copy);rewards.set(copy.id,copy)}else if(!known.image&&reward.image)known.image=reward.image}}return output}
  function addUnknownEncounter(tasks){for(const task of tasks)if((task.rewards?.filter(reward=>reward.type==="ENCOUNTER").length||0)>1&&!task.rewards.some(reward=>reward.id===UNKNOWN_ENCOUNTER.id))task.rewards.push({...UNKNOWN_ENCOUNTER});return tasks}
  function slug(value){return String(value).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
  function taskName(id){return id===REGULAR_QUEST_ID?"Checked: non event quest":plainText(state.catalogue.find(t=>t.id===id)?.text||id)}function rewardDetails(tid,rid){return state.catalogue.find(t=>t.id===tid)?.rewards.find(r=>r.id===rid)}function rewardName(tid,rid){return tid===REGULAR_QUEST_ID&&rid===REGULAR_QUEST_ID?"Non event quest":rewardDetails(tid,rid)?.label||rid}
  function sortedCatalogueTasks(){const scores=new Map();for(const reports of state.reportsByStop.values())for(const report of reports){const key=taskName(report.taskId).toLocaleLowerCase("en");scores.set(key,(scores.get(key)||0)+Math.max(1,Number(report.confirmationCount)||1))}const hasReports=scores.size>0;return state.catalogue.map((task,index)=>({task,index,key:plainText(task.text).toLocaleLowerCase("en")})).sort((a,b)=>hasReports?(scores.get(b.key)||0)-(scores.get(a.key)||0)||a.index-b.index:Number(Boolean(b.task.timedEventPriority))-Number(Boolean(a.task.timedEventPriority))||a.index-b.index).map(item=>item.task)}
  function sortedTaskRewards(task){const scores=new Map();for(const reports of state.reportsByStop.values())for(const report of reports)if(report.taskId===task?.id)scores.set(report.rewardId,(scores.get(report.rewardId)||0)+Math.max(1,Number(report.confirmationCount)||1));return(task?.rewards||[]).map((reward,index)=>({reward,index,score:scores.get(reward.id)||0})).sort((a,b)=>Number(b.score>0)-Number(a.score>0)||b.score-a.score||Number(b.reward.id===UNKNOWN_ENCOUNTER.id)-Number(a.reward.id===UNKNOWN_ENCOUNTER.id)||a.index-b.index).map(item=>item.reward)}
  function rewardPickerImage(reward){return `<span class="reward-picker-image">${reward?.image?`<img src="${escape(reward.image)}" alt="" loading="lazy" decoding="async">`:""}</span>`}
  function selectReward(rewardId){const task=state.catalogue.find(item=>item.id===$("#taskSelect").value),reward=task?.rewards.find(item=>item.id===rewardId)||task?.rewards[0];if(!reward)return;$("#rewardSelect").value=reward.id;$("#rewardPickerButton").innerHTML=`${rewardPickerImage(reward)}<span>${escape(reward.label)}</span><span class="reward-picker-arrow">▾</span>`;$$('#rewardPickerMenu .reward-picker-option').forEach(option=>option.setAttribute("aria-selected",String(option.dataset.rewardId===reward.id)));$("#rewardPickerMenu").classList.add("hidden");$("#rewardPickerButton").setAttribute("aria-expanded","false")}
  function fillTasks(){const query=$("#taskSearch").value.trim().toLocaleLowerCase("en"),tasks=sortedCatalogueTasks().filter(task=>!query||plainText(task.text).toLocaleLowerCase("en").includes(query));$("#taskSelect").innerHTML=tasks.length?tasks.map(t=>`<option value="${escape(t.id)}">${escape(plainText(t.text))}</option>`).join(""):'<option value="" disabled selected>No matching tasks</option>';$("#rewardSearch").value="";fillRewards()}
  function renderRewardOptions(){const task=state.catalogue.find(t=>t.id===$("#taskSelect").value),query=$("#rewardSearch").value.trim().toLocaleLowerCase("en"),rewards=sortedTaskRewards(task).filter(reward=>!query||reward.label.toLocaleLowerCase("en").includes(query));$("#rewardPickerMenu").innerHTML=rewards.length?rewards.map(reward=>`<button type="button" class="reward-picker-option" role="option" data-reward-id="${escape(reward.id)}" aria-selected="${$("#rewardSelect").value===reward.id}">${rewardPickerImage(reward)}<span>${escape(reward.label)}</span><span></span></button>`).join(""):'<p class="filter-empty">No matching rewards</p>';$$('#rewardPickerMenu .reward-picker-option').forEach(option=>option.addEventListener("click",()=>selectReward(option.dataset.rewardId)))}
  function fillRewards(){const task=state.catalogue.find(t=>t.id===$("#taskSelect").value),rewards=sortedTaskRewards(task);$("#rewardSelect").innerHTML=rewards.map(reward=>`<option value="${escape(reward.id)}">${escape(reward.label)}</option>`).join("");$("#rewardPickerButton").disabled=!rewards.length;$("#submitReport").disabled=!rewards.length;if(rewards.length)selectReward(rewards[0].id);else $("#rewardPickerButton").textContent="No rewards available";renderRewardOptions()}
  function updateQuestFilterButton(){const active=state.questFilter.active||!state.questFilter.showUnreported;$("#questFilterButton").classList.toggle("active",active);$("#questFilterButton").title=active?"Quest filters active":"Filter reported quests"}
  function updateQuestBulkButton(){const boxes=$$("#questFilterOptions [data-quest-keys]"),allShown=boxes.length>0&&boxes.every(box=>box.checked&&!box.indeterminate)&&$("#showUnreported").checked;$("#showAllQuests").textContent=allShown?"Hide all":"Show all";$("#showAllQuests").dataset.action=allShown?"hide":"show"}
  function taskKeys(box){return box.dataset.questKeys.split("|").filter(Boolean)}
  function syncRewardGroups(){$$('.reward-filter-group').forEach(group=>{const parent=group.querySelector('[data-reward-key]'),children=[...group.querySelectorAll('[data-quest-keys]')],checked=children.filter(box=>box.checked).length,partial=children.some(box=>box.indeterminate);parent.checked=checked===children.length&&!partial;parent.indeterminate=partial||checked>0&&checked<children.length})}
  function applyQuestFilters(){const boxes=$$("#questFilterOptions [data-quest-keys]"),selected=new Set();for(const box of boxes)if(box.checked)for(const key of taskKeys(box))selected.add(key);else if(box.indeterminate)for(const key of taskKeys(box))if(state.questFilter.selected.has(key))selected.add(key);state.questFilter.selected=selected;state.questFilter.active=boxes.some(box=>!box.checked||box.indeterminate);state.questFilter.showUnreported=$("#showUnreported").checked;saveQuestFilter();syncRewardGroups();updateQuestFilterButton();updateQuestBulkButton();renderPois()}
  function filterQuestOptions(){const query=$("#questFilterSearch").value.trim().toLowerCase();$$('.reward-filter-group').forEach(group=>group.classList.toggle("hidden",query&&!group.dataset.filterText.includes(query)))}
  function renderQuestFilters(){
    const reportedRewards=new Map();for(const reports of state.reportsByStop.values())for(const report of reports){const entry=reportedRewards.get(report.rewardId)||{reports:0,examples:[]};entry.reports++;entry.examples.push(report);reportedRewards.set(report.rewardId,entry)}
    const groups=[];for(const [rewardId,activity] of reportedRewards){const tasks=[];let reward=null;for(const task of state.catalogue){const match=task.rewards?.find(item=>item.id===rewardId);if(match){reward||=match;tasks.push({text:plainText(task.text),key:`${task.id}::${rewardId}`})}}if(!reward){const example=activity.examples[0];reward={id:rewardId,label:rewardName(example.taskId,rewardId)}}const known=new Set(tasks.map(task=>task.key));for(const report of activity.examples){const key=questKey(report);if(!known.has(key)){known.add(key);tasks.push({text:taskName(report.taskId),key})}}const combined=new Map();for(const task of tasks){const textKey=task.text.toLocaleLowerCase("en");if(!combined.has(textKey))combined.set(textKey,{text:task.text,keys:[]});combined.get(textKey).keys.push(task.key)}const uniqueTasks=[...combined.values()].sort((a,b)=>a.text.localeCompare(b.text));groups.push({reward,activity,tasks:uniqueTasks})}
    groups.sort((a,b)=>a.reward.label.localeCompare(b.reward.label));$("#showUnreported").checked=state.questFilter.showUnreported;
    $("#questFilterOptions").innerHTML=groups.length?groups.map(group=>{const image=group.reward.image?`<img src="${escape(group.reward.image)}" alt="" loading="lazy" decoding="async">`:"";const taskText=group.tasks.map(task=>task.text).join(" ").toLowerCase();return`<details class="reward-filter-group" data-filter-text="${escape(`${group.reward.label} ${taskText}`.toLowerCase())}"><summary><input type="checkbox" data-reward-key="${escape(group.reward.id)}"><span class="reward-summary-image">${image}</span><span><strong>${escape(group.reward.label)}</strong><small>${group.tasks.length} potential task${group.tasks.length===1?"":"s"} · ${group.activity.reports} report${group.activity.reports===1?"":"s"}</small></span></summary><div class="potential-task-list">${group.tasks.map(task=>{const selected=task.keys.filter(key=>state.questFilter.selected.has(key)).length,checked=!state.questFilter.active||selected===task.keys.length,partial=state.questFilter.active&&selected>0&&selected<task.keys.length;return`<label><input type="checkbox" data-quest-keys="${escape(task.keys.join("|"))}" data-partial="${partial}" ${checked?"checked":""}><span>${escape(task.text)}</span></label>`}).join("")}</div></details>`}).join(""):'<p class="filter-empty">No quests have been reported today.</p>';
    $$('#questFilterOptions [data-quest-keys]').forEach(box=>{box.indeterminate=box.dataset.partial==="true";box.addEventListener("change",applyQuestFilters)});$$('#questFilterOptions [data-reward-key]').forEach(parent=>{parent.addEventListener("click",event=>event.stopPropagation());parent.addEventListener("change",()=>{parent.closest('.reward-filter-group').querySelectorAll('[data-quest-keys]').forEach(box=>{box.checked=parent.checked;box.indeterminate=false});applyQuestFilters()})});$("#showUnreported").onchange=applyQuestFilters;syncRewardGroups();filterQuestOptions();updateQuestFilterButton();updateQuestBulkButton()
  }
  let turnstileWidget;
  function showManualQuest(show){$("#manualQuestFields").classList.toggle("hidden",!show);$("#submitReport").classList.toggle("hidden",!show);$("#otherQuest").classList.toggle("hidden",show);if(show)$("#taskSelect").focus()}
  function setPickerSearchVisible(input,visible){const button=input.id==="taskSearch"?$("#taskSearchToggle"):$("#rewardSearchToggle");input.classList.toggle("hidden",!visible);button.setAttribute("aria-expanded",String(visible));if(visible)input.focus()}
  function resetPickerSearches(){for(const input of [$("#taskSearch"),$("#rewardSearch")]){input.value="";setPickerSearchVisible(input,false)}}
  function specifyUnknownEncounter(taskId){$("#existingReportSection").classList.add("hidden");$("#taskSearch").value="";fillTasks();$("#taskSelect").value=taskId;$("#rewardSearch").value="";fillRewards();const task=state.catalogue.find(item=>item.id===taskId),firstKnown=sortedTaskRewards(task).find(reward=>reward.id!==UNKNOWN_ENCOUNTER.id);if(firstKnown)selectReward(firstKnown.id);showManualQuest(true);renderRewardOptions();$("#rewardPickerMenu").classList.remove("hidden");$("#rewardPickerButton").setAttribute("aria-expanded","true");setPickerSearchVisible($("#rewardSearch"),true)}
  async function openReport(){closeSheet();$("#reportStop").textContent=state.selected.name;const existing=state.selectedReports||[];fillTasks();const preferred=[...existing].sort((a,b)=>(b.confirmationCount||0)-(a.confirmationCount||0)||String(b.lastReportedAt||"").localeCompare(String(a.lastReportedAt||"")))[0];if(preferred&&state.catalogue.some(task=>task.id===preferred.taskId)){$("#taskSelect").value=preferred.taskId;fillRewards();selectReward(preferred.rewardId)}$("#existingReportSection").classList.toggle("hidden",!existing.length);$("#existingReportOptions").innerHTML=existing.map(report=>{const reward=rewardDetails(report.taskId,report.rewardId),unknown=report.rewardId===UNKNOWN_ENCOUNTER.id;return`<div class="existing-report-option">${rewardPickerImage(reward)}<span><strong>${escape(taskName(report.taskId))}</strong><small>${escape(rewardName(report.taskId,report.rewardId))} · ${report.confirmationCount} confirmation${report.confirmationCount===1?"":"s"}</small></span><div class="existing-report-actions"><button type="button" class="existing-confirm" data-task-id="${escape(report.taskId)}" data-reward-id="${escape(report.rewardId)}">Confirm</button>${unknown?`<button type="button" class="existing-specify" data-task-id="${escape(report.taskId)}">Specify</button>`:""}</div></div>`}).join("");showManualQuest(!existing.length);$("#reportDialog").showModal();$$('.existing-confirm').forEach(button=>button.addEventListener("click",()=>submitResearch(button.dataset.taskId,button.dataset.rewardId)));$$('.existing-specify').forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();specifyUnknownEncounter(button.dataset.taskId)}));if(CONFIG.turnstileSiteKey){$("#turnstileContainer").classList.remove("hidden");for(let i=0;i<30&&!window.turnstile;i++)await new Promise(resolve=>setTimeout(resolve,100));if(window.turnstile){if(turnstileWidget===undefined)turnstileWidget=turnstile.render("#turnstileContainer",{sitekey:CONFIG.turnstileSiteKey,theme:"dark"});else turnstile.reset(turnstileWidget)}}}
  let visibleController;
  async function loadVisible(){visibleController?.abort();const controller=new AbortController();visibleController=controller;const b=map.getBounds();if(map.getZoom()>=15)warn("Loading Wayspots…");try{rememberPois(await api(`/api/pois?minLat=${b.getSouth()}&maxLat=${b.getNorth()}&minLng=${b.getWest()}&maxLng=${b.getEast()}`,{signal:controller.signal}));if(controller.signal.aborted)return;renderPois();if(state.mode==="planner")loadCells();clearWarn()}catch(e){if(e.name==="AbortError")return;if(!CONFIG.nianticFrontendFallback){warn(e.message);return}try{rememberPois(await loadNianticPois(b,controller.signal));if(controller.signal.aborted)return;renderPois();if(state.mode==="planner")loadCells();clearWarn()}catch(fallbackError){if(fallbackError.name==="AbortError")return;if(/zoom in/i.test(fallbackError.message)){state.pois=[...state.knownPois.values()];renderPois();if(state.mode==="planner")loadCells();warn("Zoom in to see Wayspots");return}warn(`POI API failed · GraphQL fallback failed: ${fallbackError.message}`)}}}
  async function loadNianticPois(bounds,signal){
    const ids=frontendS2CellIds(bounds);
    if(!ids.length||ids.length>128)throw new Error("zoom in before using the fallback");const cacheKey=ids.slice().sort().join(","),cached=nianticCache.get(cacheKey);if(cached&&cached.expires>Date.now())return cached.pois.filter(p=>bounds.contains([p.latitude,p.longitude]));
    const sourcesByS2Cells=ids.map(s2CellId=>({s2CellId,sources:[{name:"PGO",dropTypes:["PGO_GYM","PGO_POKESTOP"]}]}));
    const response=await fetch(CONFIG.nianticGraphqlUrl,{method:"POST",mode:"cors",credentials:"omit",signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({query:NIANTIC_QUERY,variables:{input:{realityChannelId:CONFIG.nianticRealityChannelId,s2CellLevel:14,sourcesByS2Cells}}})});
    if(!response.ok)throw new Error(`Niantic returned HTTP ${response.status}`);const payload=await response.json();if(payload.errors?.length)throw new Error("Niantic returned GraphQL errors");const rows=payload.data?.realityChannelMapObjectsByS2Cells?.mapObjectsByS2CellsAndTypes;if(!Array.isArray(rows))throw new Error("unexpected Niantic response");
    const found=new Map(),seen=new Date().toISOString();for(const cell of rows)for(const group of cell.mapObjectsByType||[]){const type=group.type==="PGO_GYM"?"GYM":group.type==="PGO_POKESTOP"?"POKESTOP":null;if(!type)continue;const field=type==="GYM"?"pgoGym":"pgoPokestop";for(const object of group.mapObjects||[]){const data=object[field],location=data?.location;if(!object.id||!location)continue;const p={id:object.id,type,name:data.name||`Unnamed ${type}`,latitude:Number(location.latitude),longitude:Number(location.longitude),lastSeen:seen,s2Level17:"",s2Level14:BigInt(cell.s2CellId).toString(16).replace(/0+$/,"")};found.set(p.id,p)}}const pois=[...found.values()];nianticCache.set(cacheKey,{expires:Date.now()+120000,pois});if(nianticCache.size>20)nianticCache.delete(nianticCache.keys().next().value);return pois.filter(p=>bounds.contains([p.latitude,p.longitude]))
  }
  function frontendS2CellIds(bounds){if(!window.S2?.latLngToKey)throw new Error("S2 browser library did not load");const latSpan=bounds.getNorth()-bounds.getSouth(),lngSpan=bounds.getEast()-bounds.getWest();const rows=Math.max(1,Math.ceil(latSpan/.002)),cols=Math.max(1,Math.ceil(lngSpan/.003));if(rows>60||cols>60)throw new Error("zoom in before using the fallback");const ids=new Set();for(let y=0;y<=rows;y++)for(let x=0;x<=cols;x++){const lat=bounds.getSouth()+latSpan*y/rows,lng=bounds.getWest()+lngSpan*x/cols;ids.add(S2.keyToId(S2.latLngToKey(lat,lng,14)))}return [...ids]}
  function updatePlannerDetailAvailability(){const unavailable=map.getZoom()<15;for(const id of ["#l17","#radius20","#stopRange40","#stopRange80","#gymRange80","#rangeHotspots"]){const input=$(id);input.disabled=unavailable;input.closest("label").classList.toggle("zoom-required",unavailable)}$("#l17Hint").textContent=unavailable?"Zoom in for detail":"";const l14Unavailable=map.getZoom()<14;$("#l14").disabled=l14Unavailable;$("#l14").closest("label").classList.toggle("zoom-required",l14Unavailable);$("#l14Hint").textContent=l14Unavailable?"Zoom in for detail":""}
  function visibleS2Cells(bounds,level){if(!window.S2?.S2Cell?.FromLatLng)throw new Error("S2 browser library did not load");const center=bounds.getCenter(),first=S2.S2Cell.FromLatLng({lat:center.lat,lng:center.lng},level),queue=[first],queued=new Set([first.toHilbertQuadkey()]),cells=[];for(let i=0;i<queue.length;i++){const cell=queue[i],key=cell.toHilbertQuadkey(),polygon=cell.getCornerLatLngs().map(point=>[point.lat,point.lng]);if(!L.latLngBounds(polygon).intersects(bounds))continue;cells.push({key,polygon});if(cells.length>15000)throw new Error(`Zoom in to show Level ${level} cells`);for(const neighbor of cell.getNeighbors()){const neighborKey=neighbor.toHilbertQuadkey();if(!queued.has(neighborKey)){queued.add(neighborKey);queue.push(neighbor)}}}return cells}
  function l14GymProgress(count,gyms){const target=gyms<1?2:gyms<2?6:gyms<3?20:null;if(target===null)return{color:"#ff6b71",textColor:"#fff",priority:-10000,remaining:null,description:"Maximum observed gym threshold reached"};const remaining=Math.max(0,target-count),close=remaining<=1;return{color:close?"#52e0a4":"#ff9f43",textColor:"#082018",priority:remaining===0?10000:-remaining,remaining,description:remaining===0?"0 more Wayspots. Ready for the next gym":`${remaining} more Wayspot${remaining===1?"":"s"} until the next gym`}}
  function loadCells(){cells17.clearLayers();cells14.clearLayers();updatePlannerDetailAvailability();if(state.mode!=="planner")return;const bounds=map.getBounds(),pois=[...state.knownPois.values()].filter(p=>withinGeofence(Number(p.latitude),Number(p.longitude))),occupied17=new Set(),stats14=new Map();for(const p of pois){const key17=S2.latLngToKey(Number(p.latitude),Number(p.longitude),17),key14=S2.latLngToKey(Number(p.latitude),Number(p.longitude),14);occupied17.add(key17);const stats=stats14.get(key14)||{count:0,gyms:0};stats.count++;if(typeOf(p)==="GYM")stats.gyms++;stats14.set(key14,stats)}if($("#l17").checked&&!$("#l17").disabled)try{for(const cell of visibleS2Cells(bounds,17)){const occupied=occupied17.has(cell.key);L.polygon(cell.polygon,{renderer:cellRenderer,color:occupied?"#eafcff":"#4dbdff",weight:occupied?2.5:1,fillColor:occupied?"#168ee3":"#4dbdff",fillOpacity:occupied?.48:0,opacity:occupied?1:.38,interactive:false}).addTo(cells17)}}catch(e){warn(e.message)}if($("#l14").checked&&!$("#l14").disabled)try{const cells=visibleS2Cells(bounds,14).map(cell=>{const stats=stats14.get(cell.key)||{count:0,gyms:0};return{...cell,stats,progress:l14GymProgress(stats.count,stats.gyms)}}).sort((a,b)=>a.progress.priority-b.progress.priority);for(const cell of cells)L.polygon(cell.polygon,{renderer:cellRenderer,color:cell.progress.color,weight:2.5,fillColor:cell.progress.color,fillOpacity:.035,opacity:.95,interactive:false}).addTo(cells14);for(const cell of cells)L.marker(L.latLngBounds(cell.polygon).getCenter(),{pane:"s2Labels",icon:L.divIcon({className:"s2-count-label",html:`<span style="background:${cell.progress.color};color:${cell.progress.textColor}">${cell.stats.count}</span>`,iconSize:[30,30],iconAnchor:[15,15]})}).bindTooltip(cell.progress.description,{className:"s2-progress-tooltip",direction:"top",offset:[0,-16]}).addTo(cells14)}catch{}}
  async function loadStatic(){
    let catalogue;
    try{catalogue=await reportApi("/api/research/catalogue")}catch{try{catalogue={tasks:await loadScrapedDuckCatalogue(),stale:false};toast("Tasks loaded directly from ScrapedDuck")}catch(e){warn(`Task catalogue unavailable · ${e.message}`)}}
    if(catalogue?.tasks?.length){
      if(catalogue.tasks.some(task=>task.rewards?.some(reward=>!reward.image)))try{const artworkTasks=await loadScrapedDuckCatalogue(),artwork=new Map();for(const task of artworkTasks)for(const reward of task.rewards||[])if(reward.image)artwork.set(`${task.id}::${reward.id}`,reward.image);for(const task of catalogue.tasks)for(const reward of task.rewards||[])reward.image||=artwork.get(`${task.id}::${reward.id}`)}catch{}
      state.catalogue=addUnknownEncounter(mergeDuplicateTasks(catalogue.tasks));
    }
    try{const reports=await reportApi("/api/research"),grouped=new Map();for(const report of reports){if(!grouped.has(report.pokestopId))grouped.set(report.pokestopId,[]);grouped.get(report.pokestopId).push(report);const latitude=Number(report.latitude),longitude=Number(report.longitude);if(Number.isFinite(latitude)&&Number.isFinite(longitude)){const known=state.knownPois.get(report.pokestopId);state.knownPois.set(report.pokestopId,{...known,id:report.pokestopId,type:"POKESTOP",name:report.pokestopName||known?.name||"Reported PokéStop",latitude,longitude})}}state.reportsByStop=grouped;renderQuestFilters();renderPois()}catch(e){if(!state.catalogue.length)warn(`Report service unavailable · ${e.message}`)}
    try{const stats=await reportApi("/api/stats");const nums=[stats.reports_submitted,stats.unique_pokestops_reported,stats.confirmations,stats.conflicting_reports];$$('#stats strong').forEach((el,i)=>el.textContent=nums[i]||0);$("#progressButton").textContent=`Today · ${stats.unique_pokestops_reported||0} stops`}catch(e){if(!state.catalogue.length)warn(`Report service unavailable · ${e.message}`)}
  }
  async function loadScrapedDuckCatalogue(){const cacheKey="pokemap-research-catalogue-v2";try{const response=await fetch(CONFIG.scrapedDuckResearchUrl,{cache:"no-store",credentials:"omit"});if(!response.ok)throw new Error(`ScrapedDuck returned HTTP ${response.status}`);const rows=await response.json();if(!Array.isArray(rows))throw new Error("unexpected ScrapedDuck response");const tasks=rows.map((row,index)=>{const raw=String(row.text||"").trim(),seen=new Set();const rewards=(Array.isArray(row.rewards)?row.rewards:[]).map(reward=>{const label=String(reward.name||reward.label||"").trim(),id=slug(label),image=String(reward.image||"").trim();if(!label||!id||seen.has(id))return null;seen.add(id);return{id,label,type:"ENCOUNTER",...(image.startsWith("https://cdn.leekduck.com/")?{image}:{})}}).filter(Boolean);return raw&&rewards.length?{id:`${slug(raw)}-${index}`,text:plainText(raw),category:"research",rewards}:null}).filter(Boolean);if(!tasks.length)throw new Error("ScrapedDuck returned no tasks");localStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),tasks}));return tasks}catch(error){try{const cached=JSON.parse(localStorage.getItem(cacheKey));if(cached?.tasks?.length)return cached.tasks}catch{}throw error}}
  async function submitResearch(taskId,rewardId){if(CONFIG.turnstileSiteKey&&turnstileWidget===undefined){toast("Human verification is still loading");return}const controls=$$("#reportDialog button"),reportedStop=state.selected;controls.forEach(button=>button.disabled=true);try{const turnstileToken=turnstileWidget===undefined?null:turnstile.getResponse(turnstileWidget);await reportApi("/api/research/report",{method:"POST",body:JSON.stringify({pokestopId:reportedStop.id,taskId,rewardId,latitude:reportedStop.latitude,longitude:reportedStop.longitude,reporterId:REPORTER_ID,turnstileToken})});$("#reportDialog").close();closeSheet();playReportFireworks(Number(reportedStop.latitude),Number(reportedStop.longitude));state.selected=null;state.selectedReports=[];toast("Thank you for the report!");await loadStatic()}catch(err){toast(err.message);if(turnstileWidget!==undefined)turnstile.reset(turnstileWidget)}finally{controls.forEach(button=>button.disabled=false)}}
  function warn(text){$("#warning").textContent=text;$("#warning").classList.remove("hidden")}function clearWarn(){$("#warning").textContent="";$("#warning").classList.add("hidden")}function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
  function registerServiceWorker(){if(!("serviceWorker" in navigator))return;window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js",{scope:"./",updateViaCache:"none"}).then(registration=>registration.update()).catch(()=>{}))}
  function registerInstallButton(){const button=$("#installApp"),standalone=window.matchMedia?.("(display-mode: standalone)").matches||navigator.standalone===true,isIos=/iPad|iPhone|iPod/.test(navigator.userAgent)||navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1;if(standalone)return;let installPrompt=null;if(isIos)button.classList.remove("hidden");window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;button.classList.remove("hidden")});window.addEventListener("appinstalled",()=>{installPrompt=null;button.classList.add("hidden");toast("PoGo Boekenberg installed!")});button.addEventListener("click",async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;button.classList.add("hidden");return}if(isIos)toast("In Safari, tap Share, then Add to Home Screen")})}
  function playReportFireworks(latitude,longitude){if(!Number.isFinite(Number(latitude))||!Number.isFinite(Number(longitude))||window.matchMedia?.("(prefers-reduced-motion: reduce)").matches)return;const point=map.latLngToContainerPoint([latitude,longitude]),burst=document.createElement("div"),colors=["#52e0a4","#54b9ff","#ffbd59","#ff6b71","#c06cff"];burst.className="report-firework";burst.style.left=`${point.x}px`;burst.style.top=`${point.y}px`;for(let wave=0;wave<3;wave++)for(let i=0;i<16;i++){const particle=document.createElement("i"),angle=Math.PI*2*(i/16)+wave*.17,distance=58+wave*30+(i%3)*9;particle.style.setProperty("--firework-x",`${Math.cos(angle)*distance}px`);particle.style.setProperty("--firework-y",`${Math.sin(angle)*distance}px`);particle.style.setProperty("--firework-delay",`${wave*.14}s`);particle.style.setProperty("--firework-color",colors[(i+wave*2)%colors.length]);burst.appendChild(particle)}map.getContainer().appendChild(burst);setTimeout(()=>burst.remove(),1800)}
  let userLocationMarker,userAccuracyCircle;function showUserLocation(event){const accuracy=Math.max(0,Number(event.accuracy)||0);if(!userAccuracyCircle)userAccuracyCircle=L.circle(event.latlng,{radius:accuracy,color:"#54b9ff",weight:1.5,opacity:.8,fillColor:"#54b9ff",fillOpacity:.13,interactive:false}).addTo(locationLayer);else userAccuracyCircle.setLatLng(event.latlng).setRadius(accuracy);if(!userLocationMarker)userLocationMarker=L.circleMarker(event.latlng,{radius:7,color:"#fff",weight:3,fillColor:"#168ee3",fillOpacity:1}).bindTooltip("You are here").addTo(locationLayer);else userLocationMarker.setLatLng(event.latlng);userLocationMarker.bringToFront()}
  function closeMobileSettings(){document.body.classList.remove("mobile-settings-open");$("#settingsToggle").classList.remove("active");$("#settingsToggle").setAttribute("aria-expanded","false");$("#settingsToggle").setAttribute("aria-label","Open map settings")}
  let moveTimer,renderedZoom=map.getZoom();map.on("movestart",()=>visibleController?.abort());map.on("moveend",()=>{saveView();updatePlannerDetailAvailability();if(map.getZoom()!==renderedZoom){renderedZoom=map.getZoom();renderPois()}if(state.mode==="planner")loadCells();clearTimeout(moveTimer);moveTimer=setTimeout(loadVisible,250)});
  $$(".modes button").forEach(b=>b.addEventListener("click",()=>{$$(".modes button").forEach(x=>x.classList.toggle("active",x===b));state.mode=b.dataset.mode;document.body.classList.toggle("planner",state.mode==="planner");$("#modeTitle").textContent=state.mode==="planner"?"Inspect S2 cells":"Find today’s research";$("#modeCopy").textContent=state.mode==="planner"?"Use S2 overlays and optional Power Spot exclusion zones to evaluate Wayspot locations.":"Tap a PokéStop to view or report its current Field Research.";$("#footerCopy").textContent=state.mode==="planner"?"Live Wayspots":"Live POIs and community reports";$("#search").placeholder=state.mode==="planner"?"Search places":"Search places or rewards";closeMobileSettings();closeSheet();if(state.mode==="planner"){$$("dialog[open]").forEach(dialog=>dialog.close());if(map.getZoom()<15)map.setZoom(15);else{renderPois();loadCells()}}else{renderPois();loadCells()}}));
  $$("[data-filter],#l17,#l14,#radius20,#stopRange40,#stopRange80,#gymRange80,#rangeHotspots").forEach(x=>x.addEventListener("change",()=>{renderPois();loadCells()}));$("#search").addEventListener("input",renderPois);$("#sheetBackdrop").addEventListener("click",closeSheet);$("#taskSelect").addEventListener("change",()=>{$("#rewardSearch").value="";fillRewards()});$("#taskSearch").addEventListener("input",fillTasks);$("#rewardSearch").addEventListener("input",()=>{renderRewardOptions();$("#rewardPickerMenu").classList.remove("hidden");$("#rewardPickerButton").setAttribute("aria-expanded","true")});$$('.field-search-toggle').forEach(button=>button.addEventListener("click",()=>{const input=$(button.dataset.searchTarget),visible=input.classList.contains("hidden");setPickerSearchVisible(input,visible);if(!visible){input.value="";if(input.id==="taskSearch")fillTasks();else renderRewardOptions()}}));$("#reportDialog").addEventListener("close",resetPickerSearches);$("#refresh").addEventListener("click",()=>{loadVisible();loadStatic()});
  $("#rewardPickerButton").addEventListener("click",()=>{const menu=$("#rewardPickerMenu"),open=menu.classList.contains("hidden");menu.classList.toggle("hidden",!open);$("#rewardPickerButton").setAttribute("aria-expanded",String(open))});document.addEventListener("click",event=>{if(!event.target.closest("#rewardPicker")){$("#rewardPickerMenu").classList.add("hidden");$("#rewardPickerButton").setAttribute("aria-expanded","false")}});
  $("#questFilterButton").addEventListener("click",()=>{renderQuestFilters();$("#questFilterDialog").showModal()});
  $("#settingsToggle").addEventListener("click",()=>{const open=!document.body.classList.contains("mobile-settings-open");document.body.classList.toggle("mobile-settings-open",open);$("#settingsToggle").classList.toggle("active",open);$("#settingsToggle").setAttribute("aria-expanded",String(open));$("#settingsToggle").setAttribute("aria-label",open?"Close map settings":"Open map settings")});map.on("click",closeMobileSettings);
  $("#questFilterSearch").addEventListener("input",filterQuestOptions);
  $("#showAllQuests").addEventListener("click",()=>{const show=$("#showAllQuests").dataset.action!=="hide";$$("#questFilterOptions [data-quest-keys]").forEach(box=>{box.checked=show;box.indeterminate=false});$("#showUnreported").checked=show;applyQuestFilters()});
  $("#locate").addEventListener("click",()=>map.locate({setView:false,enableHighAccuracy:true}));map.on("locationfound",event=>{showUserLocation(event);const supported=withinGeofence(event.latitude,event.longitude);document.body.classList.toggle("location-unsupported",!supported);$("#locationWarning").classList.toggle("hidden",supported);if(supported)map.setView(event.latlng,Math.max(map.getZoom(),17))});map.on("locationerror",()=>toast("Location unavailable"));
  $("#otherQuest").addEventListener("click",()=>{$("#existingReportSection").classList.add("hidden");showManualQuest(true)});
  $("#submitReport").addEventListener("click",e=>{e.preventDefault();submitResearch($("#taskSelect").value,$("#rewardSelect").value)});
  updatePlannerDetailAvailability();renderQuestFilters();loadVisible();loadStatic();registerServiceWorker();registerInstallButton();
})();
